version: '3.7'

services:
    postgres:
        image: postgres:latest
        container_name: postgres
        env_file:
            - ./.env.prod.db
        ports:
            - 5432:5432
        volumes:
            - ./pg_data:/var/lib/postgresql/data
        restart: always

    rabbitmq:
        image: rabbitmq:3-management
        hostname: rabbitmq
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        restart: always

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - 6379:6379
        volumes:
            - ./redis_data:/data
        restart: always

    cache:
        image: memcached:latest
        container_name: cache
        ports:
            - 11211:11211

    web:
        container_name: webstore
        build:
            context: ./app
            dockerfile: Dockerfile.prod
        command: >
            bash -c "python manage.py collectstatic --noinput
            && python manage.py makemigrations
            && python manage.py migrate
            && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
        env_file:
            - ./.env.prod
        depends_on:
            - postgres
            - rabbitmq
            - redis
            - cache
        expose:
            - 8000
        volumes:
            - ./app/:/usr/src/app/
            - static_volume:/home/app/web/staticfiles
            - media_volume:/home/app/web/media
        restart: always

    celery:
        container_name: celery
        build:
            context: ./app
            dockerfile: Dockerfile.prod
        command: celery -A config worker -l INFO
        env_file:
            - ./.env.prod
        depends_on:
            - web
            - rabbitmq
        restart: always

    webserver:
        container_name: webserver
        build:
            context: ./nginx
            dockerfile: Dockerfile.nginx
        ports:
            - 1337:80
        depends_on:
            - web
        volumes:
            - static_volume:/home/app/web/staticfiles
            - media_volume:/home/app/web/media
        restart: always

volumes:
    static_volume:
    media_volume:
