version: '3.3'

services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_DB: "${DATABASE_NAME}"
            POSTGRES_USER: "${DATABASE_USER}"
            POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
            PGDATA: "/var/lib/postgresql/data"
        ports:
            - 5432:5432
        volumes:
            - ./pg_data:/var/lib/postgresql/data
        restart: always

    rabbitmq:
        hostname: rabbitmq
        image: rabbitmq:3-management
        ports:
            - 5672:5672
            - 15672:15672
        restart: always

    redis:
        image: redis:latest
        ports:
            - 6379:6379
        volumes:
            - ./redis_data:/redis_data
        restart: always

    app:
        build: .
        tty: true
        command: python manage.py runserver 0.0.0.0:8000
        environment:
            DJANGO_SETTINGS_MODULE: "${DJANGO_SETTINGS_MODULE}"
            SECRET_KEY: "${SECRET_KEY}"
            DATABASE_HOST: "${DATABASE_HOST}"
            REDIS_HOST: "${REDIS_HOST}"
        depends_on:
            - postgres
            - rabbitmq
            - redis
        ports:
            - 8000:8000
        volumes:
            - ./:/webstore
        restart: always

    celery:
        build: .
        command: celery -A config worker -l INFO
        environment:
            DJANGO_SETTINGS_MODULE: "${DJANGO_SETTINGS_MODULE}"
            SECRET_KEY: "${SECRET_KEY}"
            DATABASE_HOST: "${DATABASE_HOST}"
        depends_on:
            - app
            - rabbitmq
        restart: always
